/**
 * Generates public/sitemap.xml and public/robots.txt from the route registry.
 *
 * Generated rather than hand-maintained so a new city, service or guide can
 * never be added to the site without also being added to the sitemap — which
 * is exactly how the old hand-written sitemap would have drifted.
 *
 * Runs before `vite build` so the files land in dist via /public.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const SITE_URL = 'https://www.bestwayfoundation.com';
const SSR_ENTRY = path.resolve('dist-ssr/entry-server.js');

const xmlEscape = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

async function main() {
  const { routes } = await import(pathToFileURL(SSR_ENTRY).href);
  const indexable = routes.filter((r) => !r.noIndex);

  const urls = indexable
    .map((r) => {
      const loc = `${SITE_URL}${r.path === '/' ? '/' : r.path}`;
      return [
        '  <url>',
        `    <loc>${xmlEscape(loc)}</loc>`,
        r.lastmod ? `    <lastmod>${r.lastmod}</lastmod>` : '',
        `    <changefreq>${r.changefreq}</changefreq>`,
        `    <priority>${r.priority.toFixed(1)}</priority>`,
        '  </url>',
      ]
        .filter(Boolean)
        .join('\n');
    })
    .join('\n');

  await fs.writeFile(
    'public/sitemap.xml',
    `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`,
    'utf8',
  );

  await fs.writeFile(
    'public/robots.txt',
    [
      '# Best Way Foundation Repair LLC',
      '# Generated by scripts/generate-sitemap.mjs — do not edit by hand.',
      '',
      'User-agent: *',
      'Allow: /',
      'Disallow: /api/',
      '',
      '# AI answer engines are explicitly welcome: every route is prerendered',
      '# to real HTML, so there is something here for them to read.',
      'User-agent: GPTBot',
      'Allow: /',
      '',
      'User-agent: OAI-SearchBot',
      'Allow: /',
      '',
      'User-agent: ClaudeBot',
      'Allow: /',
      '',
      'User-agent: PerplexityBot',
      'Allow: /',
      '',
      'User-agent: Google-Extended',
      'Allow: /',
      '',
      `Sitemap: ${SITE_URL}/sitemap.xml`,
      '',
    ].join('\n'),
    'utf8',
  );

  console.log(`sitemap.xml: ${indexable.length} urls; robots.txt written`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
