/**
 * GENERATED by scripts/optimize-images.mjs — do not edit by hand.
 *
 * Intrinsic dimensions for every asset in /public/img, so <Img> can emit
 * width and height attributes and the browser can reserve space before the
 * image arrives. This is the CLS fix.
 */

export interface ImageDims {
  /** intrinsic width of the largest variant */
  w: number;
  h: number;
  /** filename without extension or width suffix */
  stem: string;
  ext: string;
  /** available widths, or null when the asset has a single size */
  widths: number[] | null;
}

export const imageMeta: Record<string, ImageDims> = {
  '/img/bbb-accredited-business.png': { w: 240, h: 120, stem: 'bbb-accredited-business', ext: '.png', widths: null },
  '/img/best-way-foundation-repair-logo.png': { w: 600, h: 200, stem: 'best-way-foundation-repair-logo', ext: '.png', widths: null },
  '/img/best-way-logo-horizontal-dark.png': { w: 640, h: 213, stem: 'best-way-logo-horizontal-dark', ext: '.png', widths: null },
  '/img/best-way-logo-horizontal.png': { w: 640, h: 213, stem: 'best-way-logo-horizontal', ext: '.png', widths: null },
  '/img/floor-joist-replacement.jpg': { w: 1200, h: 1600, stem: 'floor-joist-replacement', ext: '.jpg', widths: [640, 1024, 1200] },
  '/img/foundation-crack-inspection.jpg': { w: 1024, h: 1024, stem: 'foundation-crack-inspection', ext: '.jpg', widths: [640, 1024, 1200] },
  '/img/foundation-drainage-french-drain.jpg': { w: 1600, h: 2133, stem: 'foundation-drainage-french-drain', ext: '.jpg', widths: [640, 1024, 1600] },
  '/img/foundation-inspection-east-texas.jpg': { w: 1600, h: 2133, stem: 'foundation-inspection-east-texas', ext: '.jpg', widths: [640, 1024, 1600] },
  '/img/foundation-repair-crew-east-texas.jpg': { w: 1600, h: 2133, stem: 'foundation-repair-crew-east-texas', ext: '.jpg', widths: [640, 1024, 1600] },
  '/img/foundation-repair-longview-tx.jpg': { w: 1600, h: 2133, stem: 'foundation-repair-longview-tx', ext: '.jpg', widths: [640, 1024, 1600] },
  '/img/house-leveling-hydraulic-lift.jpg': { w: 1500, h: 1000, stem: 'house-leveling-hydraulic-lift', ext: '.jpg', widths: [640, 1024, 1600] },
  '/img/house-leveling-kilgore-tx.jpg': { w: 1600, h: 2133, stem: 'house-leveling-kilgore-tx', ext: '.jpg', widths: [640, 1024, 1600] },
  '/img/icon-drainage-solutions.png': { w: 256, h: 256, stem: 'icon-drainage-solutions', ext: '.png', widths: null },
  '/img/icon-equipment.png': { w: 256, h: 256, stem: 'icon-equipment', ext: '.png', widths: null },
  '/img/icon-foundation-repair.png': { w: 256, h: 256, stem: 'icon-foundation-repair', ext: '.png', widths: null },
  '/img/icon-house-leveling.png': { w: 256, h: 256, stem: 'icon-house-leveling', ext: '.png', widths: null },
  '/img/icon-pier-and-beam.png': { w: 256, h: 256, stem: 'icon-pier-and-beam', ext: '.png', widths: null },
  '/img/icon-repair-process.png': { w: 256, h: 256, stem: 'icon-repair-process', ext: '.png', widths: null },
  '/img/icon-wall-crack.png': { w: 256, h: 256, stem: 'icon-wall-crack', ext: '.png', widths: null },
  '/img/pier-and-beam-joist-repair.jpg': { w: 1600, h: 2133, stem: 'pier-and-beam-joist-repair', ext: '.jpg', widths: [640, 1024, 1600] },
  '/img/press-piers-installation.jpg': { w: 940, h: 788, stem: 'press-piers-installation', ext: '.jpg', widths: [640, 1024, 1600] },
  '/img/subfloor-installation.jpg': { w: 1200, h: 1600, stem: 'subfloor-installation', ext: '.jpg', widths: [640, 1024, 1200] },
};
